# config/application.yml
defaults: &defaults
  country:
    JP: 日本
    US: アメリカ合衆国
    CN: 中国
    DE: ドイツ
    TR: トルコ
    FR: フランス
    BE: ベルギー
    RU: ロシア
    IT: イタリア
    IN: インド
    KR: 韓国
    ES: スペイン
    PT: ポルトガル
    NL: オランダ
    CZ: チェコ
    IE: アイルランド
    GR: ギリシア
    IQ: アラビア
    KE: ケニア
    VN: ベトナム
    TH: タイ
    MY: マレーシア
  api:
    ghibli:
      protocol: https
      domain:   ghibliapi.herokuapp.com
      films:    films

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
